[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
[rpc_endpoints]
conflux = "${CONFLUX_RPC_URL}"

[etherscan]
conflux = { key = "${CONFLUXSCAN_API_KEY}", chain = 71, url = "${CONFLUXSCAN}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
